algolia:
  application_id: 7RXZLDVR5F
  files_to_exclude:
    - index.html
    - index.md
    - search.html
    - src/current/v23.1/**
    - v23.1/**
  index_name: stage_cockroach_docs
  search_api_key: 372a10456f4ed7042c531ff3a658771b
  settings:
    attributesForFaceting:
    - searchable(categories)
    - searchable(collection)
    - docs_area
    - searchable(tags)
    - searchable(title)
    - type
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
exclude:
- __tests__
- build
- scripts
- vendor
- jekyll-algolia-dev
- archived
- package.json
- package-lock.json
include:
- _redirects
jekyll-minifier:
  compress_css: 'false'
  compress_javascript: 'true'
  compress_js_templates: 'false'
  compress_json: 'true'
  exclude:
  - '**.html'
  - js/rapidoc-min.js
  preserve_line_breaks: 'false'
  preserve_php: 'true'
  remove_comments: 'true'
  remove_form_attributes: 'false'
  remove_http_protocol: 'false'
  remove_https_protocol: 'false'
  remove_input_attributes: 'false'
  remove_intertag_spaces: 'false'
  remove_javascript_protocol: 'false'
  remove_link_attributes: 'false'
  remove_multi_spaces: 'false'
  remove_quotes: 'false'
  remove_script_attributes: 'false'
  remove_spaces_inside_tags: 'false'
  remove_style_attributes: 'false'
  simple_boolean_attributes: 'false'
  simple_doctype: 'false'
jekyll_get_json:
- data: cloud_api_releases
  json: https://cockroachlabs.cloud/assets/docs/api/manifest.json
keep_files:
- _internal
main_url: https://www.cockroachlabs.com
markdown: Redcarpet
plugins:
- jekyll-include-cache
- jekyll-last-modified-at
- jekyll-minifier
- jekyll-get-json
sass:
  quiet_deps: 'true'
  sass_dir: css
  style: compressed
site_title: CockroachDB Docs
jekyll-include-cache:
  cache_dir: '.jekyll-cache'
  include:
    - '**/*.html'
    - '**/*.md'
    - '**/*.json'
