baseurl: /docs
current_cloud_date: '2023-09-26'
current_cloud_version: v23.1
current_dedicated_hotfix: v23.1.11
current_serverless_hotfix: v23.1.11
destination: _site/docs
homepage_title: CockroachDB Docs
versions:
  stable: v23.1
  dev: v23.2
