algolia:
  application_id: 7RXZLDVR5F
  files_to_exclude:
  - index.html
  - index.md
  - search.html
  index_name: cockroachcloud_docs
  search_api_key: 372a10456f4ed7042c531ff3a658771b
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
exclude:
- __tests__
- build
- scripts
- vendor
- jekyll-algolia-dev
- archived
- package.json
- package-lock.json
include:
- _redirects
jekyll-minifier:
  compress_css: 'false'
  compress_javascript: 'true'
  compress_js_templates: 'false'
  compress_json: 'true'
  exclude:
  - '**.html'
  - js/rapidoc-min.js
  preserve_line_breaks: 'false'
  preserve_php: 'true'
  remove_comments: 'true'
  remove_form_attributes: 'false'
  remove_http_protocol: 'false'
  remove_https_protocol: 'false'
  remove_input_attributes: 'false'
  remove_intertag_spaces: 'false'
  remove_javascript_protocol: 'false'
  remove_link_attributes: 'false'
  remove_multi_spaces: 'false'
  remove_quotes: 'false'
  remove_script_attributes: 'false'
  remove_spaces_inside_tags: 'false'
  remove_style_attributes: 'false'
  simple_boolean_attributes: 'false'
  simple_doctype: 'false'
  uglifier_args:
    harmony: 'true'
jekyll_get_json:
- data: cloud_api_releases
  json: https://cockroachlabs.cloud/assets/docs/api/manifest.json
keep_files:
- _internal
main_url: https://www.cockroachlabs.com
markdown: Redcarpet
plugins:
- jekyll-include-cache
- jekyll-last-modified-at
- jekyll-minifier
- jekyll-get-json
release_info:
  v1.0:
    build_time: 2018/02/13 15:13:51 (go1.8.3)
    docker_image: cockroachdb/cockroach
    name: v1.0.7
    start_time: 2017-02-13 13:33:22.046027038 -0400 EDT
    version: v1.0.7
  v1.1:
    build_time: 2018/10/01 14:48:26 (go1.8.3)
    docker_image: cockroachdb/cockroach
    name: v1.1.9
    start_time: 2018-10-01 15:10:52.34274101 +0000 UTC
    version: v1.1.9
  v19.1:
    build_time: 2020/07/07 14:48:26 (go1.11.6)
    docker_image: cockroachdb/cockroach
    name: v19.1.11
    start_time: 2020-07-07 15:10:52.34274101 +0000 UTC
    version: v19.1.11
  v19.2:
    build_time: 2021/01/19 11:00:26 (go1.12.12)
    docker_image: cockroachdb/cockroach
    name: v19.2.12
    start_time: 2021-01-19 11:01:26.34274101 +0000 UTC
    version: v19.2.12
  v2.0:
    build_time: 2018/12/10 14:48:26 (go1.10)
    docker_image: cockroachdb/cockroach
    name: v2.0.7
    start_time: 2018-12-10 15:10:52.34274101 +0000 UTC
    version: v2.0.7
  v2.1:
    build_time: 2019/01/29 14:48:26 (go1.10.3)
    docker_image: cockroachdb/cockroach
    name: v2.1.11
    start_time: 2019-01-29 15:10:52.34274101 +0000 UTC
    version: v2.1.11
  v20.1:
    build_time: 2021/05/17 11:00:26 (go1.13.4)
    docker_image: cockroachdb/cockroach
    name: v20.1.17
    start_time: 2021-05-17 11:01:26.34274101 +0000 UTC
    version: v20.1.17
  v20.2:
    build_time: 2022/02/09 11:00:26 (go1.13.4)
    docker_image: cockroachdb/cockroach
    name: v20.2.19
    start_time: 2022-02-09 11:01:26.34274101 +0000 UTC
    version: v20.2.19
  v21.1:
    build_time: 2022-09-15 00:00:00 (go1.17)
    crdb_branch_name: release-21.1
    docker_image: cockroachdb/cockroach
    name: v21.1.21
    start_time: 2022-09-14 12:48:52.570761 +0000 UTC
    version: v21.1.21
  v21.2:
    build_time: 2022-10-17 00:00:00 (go1.18)
    crdb_branch_name: release-21.2
    docker_image: cockroachdb/cockroach
    name: v21.2.17
    start_time: 2022-10-13 17:45:03.909127 +0000 UTC
    version: v21.2.17
  v22.1:
    build_time: 2023-02-17 00:00:00 (go1.19)
    crdb_branch_name: release-22.1
    docker_image: cockroachdb/cockroach
    name: v22.1.15
    start_time: 2023-02-14 13:12:08.430158 +0000 UTC
    version: v22.1.15
  v22.2:
    build_time: 2023-02-16 00:00:00 (go1.19)
    crdb_branch_name: release-22.2
    docker_image: cockroachdb/cockroach
    name: v22.2.5
    start_time: 2023-02-16 11:31:24.747610 +0000 UTC
    version: v22.2.5
  v23.1:
    build_time: 2022-02-13 00:00:00 (go1.19)
    crdb_branch_name: master
    docker_image: cockroachdb/cockroach-unstable
    name: v23.1.0-alpha.2
    start_time: 2023-02-13 12:50:35.356959 +0000 UTC
    version: v23.1.0-alpha.2
sass:
  sass_dir: css
  style: compressed
site_title: CockroachDB Docs
