homepage_title: CockroachDB Docs
site_title: Cockroach Labs

url: "https://www.cockroachlabs.com"
baseurl: "/docs"

gems:
- jekyll-sitemap

highlighter: rouge
markdown: redcarpet

redcarpet:
  extensions:
  - disable_indented_code_blocks
  - no_intra_emphasis
  - tables
  - with_toc_data

versions:
  stable: v1.1
  dev: v2.0
  v1.2: v2.0

release_info:
  v1.0:
    version: v1.0.6
    docker_image: cockroachdb/cockroach
    build_time: 2017/09/14 15:13:51 (go1.8.3)
    start_time: 2017-09-14 13:33:22.046027038 -0400 EDT
  v1.1:
    name: v1.1.5
    version: v1.1.5
    docker_image: cockroachdb/cockroach
    build_time: 2018/02/05 14:48:26 (go1.8.3)
    start_time: 2018-02-05 15:10:52.34274101 +0000 UTC
  v2.0:
    name: v2.0-alpha
    version: v2.0-alpha.20180129
    docker_image: cockroachdb/cockroach-unstable
    build_time: 2018/01/29 14:48:26 (go1.9)
    start_time: 2018-01-29 15:10:52.34274101 +0000 UTC

training:
  ccl_license: crl-0-ELzpyNMFGAIiF0NvY2tyb2FjaCBMYWJzIFRyYWluaW5n
  aws_access_key: AKIAJNRF52TMSNX
  aws_secret_access_key: 6yTKDp5GHihUdVvBwUtj5PZYSSBUK3s6lQb7

exclude: ["ci", "vendor", "rfc"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
