baseurl: /docs
current_cloud_date: '2023-04-10'
current_cloud_version: v22.2
current_dedicated_hotfix: v22.2.7
current_serverless_hotfix: v22.2.7
destination: _site/docs
homepage_title: CockroachDB Docs
versions:
  dev: v23.1
  stable: v22.2
