site_title: CockroachDB Docs
url: "https://www.cockroachlabs.com"

plugins:
- jekyll-sitemap

markdown: Redcarpet

release_info:
  v1.0:
    name: v1.0.7
    version: v1.0.7
    docker_image: cockroachdb/cockroach
    build_time: 2017/02/13 15:13:51 (go1.8.3)
    start_time: 2017-02-13 13:33:22.046027038 -0400 EDT
  v1.1:
    name: v1.1.9
    version: v1.1.9
    docker_image: cockroachdb/cockroach
    build_time: 2018/10/01 14:48:26 (go1.8.3)
    start_time: 2018-10-01 15:10:52.34274101 +0000 UTC
  v2.0:
    name: v2.0.7
    version: v2.0.7
    docker_image: cockroachdb/cockroach
    build_time: 2018/12/10 14:48:26 (go1.10)
    start_time: 2018-12-10 15:10:52.34274101 +0000 UTC
  v2.1:
    name: v2.1.9
    version: v2.1.9
    docker_image: cockroachdb/cockroach
    build_time: 2019/07/23 14:48:26 (go1.10.3)
    start_time: 2019-07-23 15:10:52.34274101 +0000 UTC
  v19.1:
    name: v19.1.5
    version: v19.1.5
    docker_image: cockroachdb/cockroach
    build_time: 2019/09/30 14:48:26 (go1.11.6)
    start_time: 2018-09-30 15:10:52.34274101 +0000 UTC
  v19.2:
    name: v19.2.0
    version: v19.2.0
    docker_image: cockroachdb/cockroach
    build_time: 2019/11/12 11:00:26 (go1.12.12)
    start_time: 2019-11-12 11:01:26.34274101 +0000 UTC
  v20.1:
    name: v20.1.0
    version: v20.1.0-alpha.20191118
    docker_image: cockroachdb/cockroach-unstable
    build_time: 2019/11/18 11:00:26 (go1.12.12)
    start_time: 2019-11-18 11:01:26.34274101 +0000 UTC

include: ["_redirects"]
exclude:
- "ci"
- "scripts"
- "vendor"
- "hackathon.md"

keep_files: [_internal]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
