homepage_title: CockroachDB Docs
site_title: CockroachDB

url: "https://www.cockroachlabs.com"
baseurl: "/docs"
destination: _site/docs

gems:
- jekyll-sitemap

highlighter: rouge
markdown: redcarpet

redcarpet:
  extensions:
  - disable_indented_code_blocks
  - no_intra_emphasis
  - tables
  - with_toc_data

versions:
  stable: v2.0
  dev: v2.0
  v1.2: v2.0
  v2.1: v2.0

release_info:
  v1.0:
    version: v1.0.7
    docker_image: cockroachdb/cockroach
    build_time: 2017/02/13 15:13:51 (go1.8.3)
    start_time: 2017-02-13 13:33:22.046027038 -0400 EDT
  v1.1:
    name: v1.1.7
    version: v1.1.7
    docker_image: cockroachdb/cockroach
    build_time: 2018/03/26 14:48:26 (go1.8.3)
    start_time: 2018-03-26 15:10:52.34274101 +0000 UTC
  v2.0:
    name: v2.0
    version: v2.0.0
    docker_image: cockroachdb/cockroach
    build_time: 2018/04/04 14:48:26 (go1.10)
    start_time: 2018-04-04 15:10:52.34274101 +0000 UTC
  # v2.1:
  #   name: v2.1
  #   version: v2.0.0
  #   docker_image: cockroachdb/cockroach-unstable
  #   build_time: 2018/03/26 14:48:26 (go1.10)
  #   start_time: 2018-03-26 15:10:52.34274101 +0000 UTC

training:
  ccl_license: crl-0-EIDA4OgGGAEiF0NvY2tyb2FjaCBMYWJzIFRyYWluaW5n
  aws_access_key: AKIAIXNAWDKXMDDNHRCA
  aws_secret_access_key: wVevB0LO5CDf5lxI9tpy%2FXuE0UZi%2Bmpahiwoa3YL

exclude: ["ci", "vendor", "rfc", "v1.1/training/unused", "v2.0/training/unused"]

keep_files: [_internal]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
