homepage_title: CockroachDB Docs
site_title: Cockroach Labs

url: "https://www.cockroachlabs.com"
baseurl: "/docs"

gems:
- jekyll-sitemap

highlighter: rouge
markdown: redcarpet

redcarpet:
  extensions:
  - disable_indented_code_blocks
  - no_intra_emphasis
  - tables
  - with_toc_data

versions:
  stable: v1.0
  dev: v1.1

release_info:
  v1.0:
    version: v1.0.4
    build_time: 2017/07/27 12:56:53 (go1.8.3)
    start_time: 2017-07-27 10:29:13.675508543 -0400 EDT
  v1.1:
    name: v1.1-alpha
    version: v1.1-alpha.20170803
    build_time: 2017/08/03 15:21:15 (go1.8.3)
    start_time: 2017-08-03 18:53:43.318460386 -0400 EDT

exclude: ["ci", "vendor"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
