site_title: CockroachDB Docs
url: "https://www.cockroachlabs.com"

gems:
- jekyll-sitemap

highlighter: rouge
markdown: redcarpet

redcarpet:
  extensions:
  - disable_indented_code_blocks
  - no_intra_emphasis
  - tables
  - with_toc_data

release_info:
  v1.0:
    name: v1.0.7
    version: v1.0.7
    docker_image: cockroachdb/cockroach
    build_time: 2017/02/13 15:13:51 (go1.8.3)
    start_time: 2017-02-13 13:33:22.046027038 -0400 EDT
  v1.1:
    name: v1.1.9
    version: v1.1.9
    docker_image: cockroachdb/cockroach
    build_time: 2018/10/01 14:48:26 (go1.8.3)
    start_time: 2018-10-01 15:10:52.34274101 +0000 UTC
  v2.0:
    name: v2.0.7
    version: v2.0.7
    docker_image: cockroachdb/cockroach
    build_time: 2018/12/10 14:48:26 (go1.10)
    start_time: 2018-12-10 15:10:52.34274101 +0000 UTC
  v2.1:
    name: v2.1.3
    version: v2.1.3
    docker_image: cockroachdb/cockroach
    build_time: 2018/12/17 14:48:26 (go1.10.3)
    start_time: 2018-12-17 15:10:52.34274101 +0000 UTC
  v2.2:
    name: v2.2
    version: v2.2.0-alpha.20190114
    docker_image: cockroachdb/cockroach-unstable
    build_time: 2019/01/14 14:48:26 (go1.10.3)
    start_time: 2018-01-14 15:10:52.34274101 +0000 UTC

training:
  ccl_license: crl-0-EIDA4OgGGAEiF0NvY2tyb2FjaCBMYWJzIFRyYWluaW5n
  aws_access_key: AKIAIXNAWDKXMDDNHRCA
  aws_secret_access_key: wVevB0LO5CDf5lxI9tpy%2FXuE0UZi%2Bmpahiwoa3YL

include: ["_redirects"]
exclude: ["ci", "vendor", "v1.1/training/unused", "v2.0/training/unused", "v2.1/training/unused", "v2.2/training/unused", "hackathon.md"]

keep_files: [_internal]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
