extends: substitution
message: Prefer '%s' over '%s'
ignorecase: false
level: warning
swap:
  builtin: built-in
  builtins: built-ins
  '[^\/\-\.]cockroachdb[^\/\-\.]': CockroachDB
  'CockroachCloud Serverless': "{{ site.data.products.serverless }}"
  'CockroachCloud Dedicated': "{{ site.data.products.dedicated }}"
  'CockroachDB Serverless': "{{ site.data.products.serverless }}"
  'CockroachDB Dedicated': "{{ site.data.products.dedicated }}"
  CockroachCloud: "{{ site.data.products.db }}"
  Enterprise: Enterprise
  raft: Raft
  Raft Group: Raft group
  Admin UI: DB Console
  admin ui: DB Console
  web UI: DB Console
  web UI: DB Console
  ui: UI
  Distribution Layer: distribution layer
  Replication Layer: replication layer
  SQL Layer: SQL layer
  Storage Layer: storage layer
  Transaction Layer: transaction layer
  Leaseholder: leaseholder
  Key-Value: key-value
  Replication Zone: replication zone
  Replication Zones: replication zones
  Write Intent: write intent
  Transaction Record: transaction record
  Timestamp Cache: timestamp cache
  Check constraint: "`CHECK` constraint"
  Default Value constraint: "`DEFAULT` value constraint"
  Not Null constraint: "`NOT NULL` constraint"
  Primary Key constraint: "`PRIMARY KEY` constraint"
  Unique constraint: "`UNIQUE` constraint"
  Postgres: PostgreSQL
